#! /bin/bash

APACHEDIR="/etc/apache2/sites-available"
APACHETEMPLATE="apache-vhost-template.conf"
DOMAINNAME="$1"
DOCUMENTROOT="$2"
ADMINUSER="$3"

if [ "$DOMAINNAME" == "" ]
then
    echo "faltou DOMAINNAME"
    echo "uso: ime-gen-vhost <domain_name_non_fqdn> [document_root] [admin]"
    exit
fi

if [ "$DOCUMENTROOT" == "" ]
then
    DOCUMENTROOT=$(getent passwd $DOMAINNAME | cut -d: -f6)/www
else
    grep www <<< $DOCUMENTROOT
    if [ $? -ne 0 ]
    then
        echo "não encontrei www no PATH. tem certeza?"
        read CERTEZA
        if [[ "$CERTEZA" != [sS]* ]]
        then
            exit
        fi
    fi
fi

if [ "$ADMINUSER" == "" ]
then
    ADMINUSER=$DOMAINNAME
fi

cd /root/vhost
sed -e 's|DOMAINNAME|'$DOMAINNAME'|' -e 's|DOCUMENTROOT|'$DOCUMENTROOT'|' -e 's|ADMINUSER|'$ADMINUSER'|' $APACHETEMPLATE > $APACHEDIR/$DOMAINNAME.conf
a2ensite $DOMAINNAME

echo vhost $DOMAINNAME.ime.usp.br criado. reiniciando o apache.
/usr/sbin/service apache2 reload

echo propagando para o nginx.
/usr/bin/ssh vhost@cache sudo /usr/local/bin/ime-gen-vhost $DOMAINNAME

echo não se esqueça do DNS.
